# Generated by Django 4.2.4 on 2023-08-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('ph_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.BigIntegerField()),
                ('position', models.CharField(max_length=30)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easemybiz_app.gender')),
            ],
        ),
    ]
