# Generated by Django 4.2.4 on 2023-08-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easemybiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('due_datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easemybiz_app.employee')),
            ],
        ),
    ]
