# Generated by Django 4.2.4 on 2023-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easemybiz_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='In-progress', max_length=20),
        ),
    ]
