# Generated by Django 4.2.4 on 2023-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easemybiz_app', '0004_remove_task_status_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
