# Generated by Django 4.2.4 on 2023-08-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easemybiz_app', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('appointment_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
